#!/bin/sh
set -e 
export DEPLOY_USER_HOME="/home/deploy"

DEPLOY="$DEPLOY_USER_HOME/deployment"
export PYTHONPATH="$DEPLOY_USER_HOME/src/qoorateserver/apps:~/src/brubeck"
  
cd $DEPLOY

# WARNING: on some systems the nohup doesn't work, like OSX 
# try running it without 
nohup python -u $DEPLOY/apps/qoorateserver/main.py 2>&1 >> $DEPLOY/logs/qoorateserver.log & 
echo $! > $DEPLOY/run/qoorateserver/pid
